# Generated by Django 5.0.6 on 2024-06-11 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cpasisApp', '0005_alter_indicador_nome_indicador_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='indicador',
            name='foto_indicador',
            field=models.ImageField(blank=True, upload_to=''),
        ),
    ]
